defaults:
  - _self_

random_seed: 42

training:
  multi_class: false
  batch_size: 256
  max_epochs: 2
      
  optimizer: "adam"
  learning_rate: 0.005
  lr_decay: true
  lr_decay_rate: 0.05
  weight_decay: 0.001

  LAMBD_2: 0.01
  dropout: true
  dropout_rate: 0.2
  batch_norm: true 


fl:
  num_rounds: 15
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  num_clients: 5
  min_fit_clients: 5
  min_evaluate_clients: 5
  min_available_clients: 5

models:
  - mlp
  - cnn
  # - cnn_lstm

logging:
  selected_type: "wandb"
  wandb:
    project: "FL-GDLC-exp2-small"
    entity: "mtermos-cesi"
    tags: ["exp2_small", "cic_ton_iot_5_percent"]
    save_dir: "logs/wandb_runs"
  tensorboard:
    project: "FL-GDLC-exp2-small"
    save_dir: "logs/tensorboard_runs"

datasets:
  datasets_list:
    - dataset_properties:
        name: "cic_ton_iot_5_percent"
        raw: "cic_ton_iot_5_percent.parquet"
        raw_type: "parquet"
        num_clients: 5
        global_test_size: 0.1
        src_ip_col: "Src IP"
        dst_ip_col: "Dst IP" 
        timestamp_col: "Timestamp"
        flow_id_col: "Flow ID"
        timestamp_format: "%d/%m/%Y %I:%M:%S %p"
        label_col: "Label"
        class_col: "Attack"
        class_num_col: "Class"
        drop_columns:
          - Flow ID
          - Src IP
          - Dst IP
          - Timestamp
          - Src Port
          - Dst Port
          - Attack
        weak_columns:
          - Bwd PSH Flags
          - Fwd URG Flags
          - Bwd URG Flags
          - URG Flag Cnt
          - Fwd Byts/b Avg
          - Fwd Pkts/b Avg
          - Fwd Blk Rate Avg
          - Subflow Bwd Pkts
          - Flow IAT Mean
          - Fwd Pkt Len Max
          - Flow IAT Max
          - Active Std
          - Bwd Header Len
          - Tot Bwd Pkts
          - Bwd Pkt Len Mean
          - Pkt Size Avg
          - Fwd Seg Size Avg
          - Bwd Seg Size Avg
          - CWE Flag Count
          - Bwd IAT Tot
          - Fwd IAT Mean
          - Fwd Pkt Len Std
          - Pkt Len Mean
          - Flow IAT Min
          - TotLen Bwd Pkts
          - Bwd Pkt Len Max
          - Pkt Len Var
          - FIN Flag Cnt
          - Bwd IAT Mean
          - Idle Mean
          - Pkt Len Max
          - Flow Pkts/s
          - Flow Duration
          - Pkt Len Std
          - Fwd IAT Tot
          - PSH Flag Cnt
          - Active Mean
          - Bwd Pkt Len Std
          - Fwd Pkt Len Mean

  processed_dir: "datasets/exp2_small"
  label_col: "Label"
  class_col: "Attack"
  class_num_col: "Class"
  val_size: 0.1
  drop_columns:
    - Flow ID
    - Src IP
    - Dst IP
    - Timestamp
    - Src Port
    - Dst Port
    - Attack

  weak_columns:
    - Flow Duration
    - Tot Bwd Pkts
    - TotLen Bwd Pkts
    - Fwd Pkt Len Max
    - Fwd Pkt Len Mean
    - Bwd Pkt Len Max
    - Bwd Pkt Len Mean
    - Bwd Pkt Len Std
    - Flow Pkts/s
    - Flow IAT Mean
    - Flow IAT Max
    - Fwd IAT Mean
    - Bwd IAT Mean
    - Pkt Len Max
    - Pkt Len Mean
    - Pkt Size Avg
    - Fwd Byts/b Avg
    - Fwd Pkts/b Avg
    - Fwd Blk Rate Avg
    - Active Mean
    - Idle Mean
