random_seed: 42

experiment:
  name: "exp3"
  description: "An FL environment created using the cic_ids_2017 dataset."

training:
  multi_class: false
  batch_size: 256
  max_epochs: 2

  optimizer: "adam"
  learning_rate: 0.005
  lr_decay: true
  lr_decay_rate: 0.05
  weight_decay: 0.001

  LAMBD_2: 0.01
  dropout: true
  dropout_rate: 0.2
  batch_norm: true

fl:
  num_rounds: 50
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  num_clients: 3
  min_fit_clients: 3
  min_evaluate_clients: 3
  min_available_clients: 3

logging:
  selected_type: "wandb"
  wandb:
    project: "FL-GDLC-exp3"
    entity: "mtermos-cesi"
    tags: [ "exp3", "cic_ids_2017" ]
    save_dir: "logs/wandb_runs"
  tensorboard:
    project: "FL-GDLC-exp3"
    save_dir: "logs/tensorboard_runs"

datasets:
- name: "cic_ids_2017"
  raw: "cic_ids_2017.parquet"
  raw_type: "parquet"
  num_clients: 3
  global_test_size: 0.1

dataset_properties:
  processed_dir: "datasets/exp3"
  src_ip_col: "Src IP"
  dst_ip_col: "Dst IP"
  timestamp_col: "Timestamp"
  flow_id_col: "Flow ID"
  timestamp_format: "%d/%m/%Y %I:%M:%S %p"
  label_col: "Label"
  class_col: "Attack"
  class_num_col: "Class"
  val_size: 0.1
  drop_columns: [ "Flow ID", "Src IP", "Dst IP", "Timestamp", "Src Port", "Dst Port", "Attack" ]
  weak_columns: [ "Flow Duration", "Tot Bwd Pkts", "TotLen Bwd Pkts", "Fwd Pkt Len Max", "Fwd Pkt Len Mean", "Bwd Pkt Len Max", "Bwd Pkt Len Mean", "Bwd Pkt Len Std", "Flow Pkts/s", "Flow IAT Mean", "Flow IAT Max", "Fwd IAT Mean", "Bwd IAT Mean", "Pkt Len Max", "Pkt Len Mean", "Pkt Size Avg", "Fwd Byts/b Avg", "Fwd Pkts/b Avg", "Fwd Blk Rate Avg", "Active Mean, Idle Mean" ]
