multi_class: true
# batch_size: 256
# batch_size: 1024
batch_size: 2048
max_epochs: 1
centralized_max_epochs: 2
sequence_length: 3

optimizer: "adam"
learning_rate: 1e-3
# learning_rate: 5e-4
# learning_rate: 1e-4
# learning_rate: 5e-5
# learning_rate: 1e-5

lr_decay: true
lr_decay_rate: 0.05
weight_decay: 0.001

# use_weighted_loss: True
use_weighted_loss: False
weighted_loss_version: "v4"

# loss_type: "cross_entropy"
loss_type: "focal"
focal_loss_alpha: 1.0
focal_loss_gamma: 2.0
focal_loss_reduction: 'sum'
# focal_loss_reduction: 'mean'

# fl_strategy: "FedAvg"
# fl_strategy: "FedDyn"
# fl_strategy: "FedBN"
# fl_strategy: "FedNoAgg"
fl_strategy: "FedProx"
fl_proximal_mu: 0.75

oversample: True
