multi_class: true
batch_size: 1024
max_epochs: 1

optimizer: "adam"
learning_rate: 0.00001
lr_decay: true
lr_decay_rate: 0.1
weight_decay: 0.01

# use_weighted_loss: true
use_weighted_loss: false
weighted_loss_version: "v4"

# loss_type: "cross_entropy"
loss_type: "focal"
focal_loss_alpha: 1.0
focal_loss_gamma: 2.0
focal_loss_reduction: 'sum'
# focal_loss_reduction: 'mean'

# fl_strategy: "FedAvg"
# fl_strategy: "FedDyn"
# fl_strategy: "FedBN"
# fl_strategy: "FedNoAgg"
fl_strategy: "FedProx"
fl_proximal_mu: 0.75

oversample: true
